FROM node:24-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=yarn.lock,target=yarn.lock \
    --mount=type=cache,target=/root/.yarn \
    yarn install
COPY package.json .
CMD ["yarn", "start:lwatch"]