FROM node:24-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=yarn.lock,target=yarn.lock \
    --mount=type=cache,target=/root/.yarn \
    yarn install --production --frozen-lockfile
COPY src src
COPY package.json .
CMD ["yarn", "start"]