apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-storage
  template:
    metadata:
      labels:
        app: azure-storage
    spec:
      containers: 
      - name: azure-storage
        image: $CONTAINER_REGISTRY/azure-storage:$VERSION
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "3001"
          - name: STORAGE_ACCOUNT_NAME
            value: "$STORAGE_ACCOUNT_NAME"
          - name: STORAGE_ACCESS_KEY
            value: "$STORAGE_ACCESS_KEY"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-storage
spec:
  selector:
    app: azure-storage
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001